name: audio-services workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  transcribe-cli:
    uses: ./.github/workflows/transcribe.yml
