name: audio-services workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.12.4,<3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          make lint
      - name: Test with pytest
        run: |
          make test
      - name: Build transcribe CLI
        run: |
          make build-transcribe
      - name: Archive transcribe binary
        run: |
          tar -czvf transcribe.tar.gz dist/transcribe
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: transcribe
          path: transcribe.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: transcribe
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./transcribe.tar.gz
          asset_name: transcribe.tar.gz
          asset_content_type: application/gzip
