name: audio-services workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image and create the artifact
      - name: Build Docker Image
        run: |
          make build-docker-transcribe

      - name: Run Docker Container to Build Artifact
        run: |
          docker run --rm -v ${{ github.workspace }}/dist:/usr/src/app/dist audio-services

      - name: Archive transcribe binary
        run: |
          make archive-transcribe-artifacts

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: transcribe
          path: transcribe.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: transcribe
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./transcribe.tar.gz
          asset_name: transcribe.tar.gz
          asset_content_type: application/gzip
