name: transcribe build,test and release

on:
  workflow_call:

permissions:
  contents: write

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image and create the artifact
      - name: Build Docker Image
        run: |
          make build-transcribe-image

      - name: Lint project
        run: |
          make lint-transcribe-docker

      - name: Perform unit tests
        run: |
          make test-transcribe-docker

      # Largely a smoke test at this point to ensure it compiles fine
      - name: Build Binary CLI
        if: contains(github.ref, 'main')
        run: |
          make build-transcribe-docker
